// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Header from './Header/index.svelte';
import RichText from './RichText/index.svelte';

export const components = {
	about: About,
	header: Header,
	rich_text: RichText
};
