// Code generated by Slice Machine. DO NOT EDIT.

import About from './About/index.svelte';
import Gallery from './Gallery/index.svelte';
import Header from './Header/index.svelte';
import RichText from './RichText/index.svelte';
import Showcase from './Showcase/index.svelte';

export const components = {
	about: About,
	gallery: Gallery,
	header: Header,
	rich_text: RichText,
	showcase: Showcase
};
